apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-2-devfile-sample-python-basic-z7ca-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-2-devfile-sample-python-basic-z7ca-sample
    app.kubernetes.io/part-of: application-2
  name: application-2-devfile-sample-python-basic-z7ca-sample
  namespace: sbudhwar-1-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: application-2-devfile-sample-python-basic-z7ca-sample
    weight: 100
status: {}
